# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Daeyong AHN
baseurl:        ""
url:            "https://dragonyongs.github.io/"
timezone:       Asia/Seoul

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Daeyong AHN
  url:          http://daeyong.github.io/
  email:        dragonyongs@naver.com
  github:       dragonyongs
  twitter:      soondae4u

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/dragonyongs/daeyong.github.io
